spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=Asia/Seoul
    username: root
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
